# Ruff configuration for Langbase Python SDK

# Same line length as Black
line-length = 88

# Target Python 3.7+
target-version = "py37"

# Enable various lint rules
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
    "EM",   # flake8-errmsg
    "ISC",  # flake8-implicit-str-concat
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
    "PL",   # pylint
    "RUF",  # ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E501",   # line too long (handled by Black)
    "PLR0913", # too many arguments
    "PLR2004", # magic value comparison
]

# Exclude directories
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".venv",
]

# Allow unused variables when prefixed with underscore
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Allow autofix for all enabled rules
fix = true

[per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]

# Allow assert statements in test files
"tests/*.py" = ["S101", "PLR2004"]

# Allow print statements and magic values in examples
"examples/*.py" = ["T201", "PLR2004"]